### ISSUE TITLE
PRTG XML Option

### ISSUE THREAD

**Issue by jefflovesjulie** [Tux/speedtest#10] opened 2018-04-27 18:03 UTC
Hi -

I’m trying to use your app with the PRTG option, and it seems it’s no longer there. 

I’m not a programmer. Could you tell me what I’m doing wrong, or how to fix?

**Comment by Tux** [comment] 2018-04-28 07:38
There are too many options here that could be "the cause"
1. Your system downgraded the App to a version that did not yet have the option
2. You've got multiple versions installed and you choose the old one
3. You mistyped the option
4. You used the short (-P) version of the option, but used the lower-case 'p', meaning --ping
5. You mistyped the option
If you don't show the exact call and the output it gives instead, I don't think I can give a conclusive answer. I just tried it here, and all worked as expected.

**Comment by Tux** [comment] 2018-09-13 13:02
Closed as there is no feedback to take action on. Feel free to re-open if you do.

**Closed by Tux** 2018-09-13 13:02 UTC
